name = "portfolio"  # Replace with your actual project name

kv_namespaces = [
  { id = "MY_KV", binding = "MY_KV" }
]

compatibility_flags = ["nodejs_compat"]

pages_build_output_dir = "./build/client"
